name: gym_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.5+1
  table_calendar: ^3.2.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.0.0
  google_sign_in: ^6.0.0
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Google.webp
